### ISSUE TITLE
Error en la entrada de un valor no entero

### ISSUE THREAD

**Issue by ctiglla** [jnicoll12/TriviaRuiz#1]
**DESCRIPCIÓN**

En la línea 11 al solicitar la entrada de la edad, el usuario podría escribir una cadena que no se podría convertir en un entero dando un ValueError.

**POSIBLE SOLUCIÓN**
Se podría incluir un while try para obligar al usuario a introducir un valor convertible a tipo int

`while True:
    edad = (input("Escribe tu edad: "))
    try:
        edad = int(edad)
        break
    except ValueError:
        print("La edad es un numero entero")`

![Captura](https://user-images.githubusercontent.com/113260231/190832781-90016eaf-812a-429b-94cc-4e5bceabac3e.PNG)

**Comment by jnicoll12** [comment]
Se acabar de solucionar, con lo recomendado
